package org.vaadin.example.bookstore;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.binder.PropertyId;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
//@Design
//@AutoGenerated
@SuppressWarnings("serial")
public class CustomerFormDesign extends FormLayout {
	@PropertyId("firstName")
	protected TextField firstName = new TextField();;
	@PropertyId("lastName")
	protected TextField lastName = new TextField();;
	@PropertyId("email")
	protected TextField email = new TextField();;
	@PropertyId("status")
	protected Select<CustomerStatus> status = new Select<>();;
	@PropertyId("birthDate")
	protected DatePicker birthDate = new DatePicker();
	protected Button save = new Button("Save");
	protected Button delete = new Button("Delete");

	public CustomerFormDesign() {
		HorizontalLayout h1layout = new HorizontalLayout();
		Label nameLabel = new Label("Name");
		firstName.setPlaceholder("First");
		lastName.setPlaceholder("Last");
		h1layout.add(firstName, lastName);
		email.setPlaceholder("Email");
		email.setLabel("Email");
		status.setLabel("Status");
		birthDate.setLabel("Birthday");
		HorizontalLayout h2Layout = new HorizontalLayout();
		h2Layout.add(save, delete);
		add(h1layout, email, status, birthDate, h2Layout);
	}
}
